### ISSUE TITLE
Loading grammar with highlights throws missing scopeName property error

### ISSUE THREAD

**Issue by austinkelleher** [atom/first-mate#106]
### Description

We are using the `language-javascript` package (along with several others) in combination with [highlights](https://github.com/atom/highlights) to syntax highlight a REPL on a webpage. It seems that sometime recently new grammar files were added without a `scopeName` property (e.g. https://github.com/atom/language-javascript/blob/master/grammars/tree-sitter-javascript.cson) and instead are using `legacyScopeName`. This is causing an error to be thrown from `first-mate` as it is expecting a `scopeName` property. I'm not sure what the right solution is to this. We could either:

1. Add a `scopeName` property to each of the grammar files that is missing it
2. Add support for `legacyScopeName` in this module

I'm leaning towards 2 as the better solution, but I'm not really sure why `legacyScopeName` was introduced in the first place. I would be happy to work on this and submit a PR given proper feedback on the above information.

**Case:**

```js
const Highlights = require("highlights");

const highlighter = new Highlights();

highlighter.requireGrammarsSync({
  modulePath: require.resolve("language-javascript/package.json")
});
```

**Throws the following error:**

```
Caused by: Error: Grammar missing required scopeName property: /node_modules/language-javascript/grammars/tree-sitter-javascript.cson
  at GrammarRegistry.module.exports.GrammarRegistry.readGrammarSync (/node_modules/first-mate/lib/grammar-registry.js:107:15)
  at GrammarRegistry.module.exports.GrammarRegistry.loadGrammarSync (/node_modules/first-mate/lib/grammar-registry.js:133:22)
  at Highlights.module.exports.Highlights.requireGrammarsSync (/node_modules/highlights/lib/highlights.js:95:25)
```

/cc @50Wliu @maxbrunsfeld

**Comment by 50Wliu** [comment]
Tracking in atom/atom#16581.

**Comment by 50Wliu** [comment]
Actually that is related but not quite the same.

**Comment by austinkelleher** [comment]
Do have any thoughts on a fix @50Wliu?

**Comment by 50Wliu** [comment]
I will defer to @maxbrunsfeld who is working on tree-sitter.

**Comment by austinkelleher** [comment]
@maxbrunsfeld Any thoughts on this? This bug is currently breaking our REPL for: https://markojs.com/try-online/

**Comment by austinkelleher** [comment]
Ping @maxbrunsfeld @50Wliu following up with this issue since there is still no consensus. Thoughts on my suggested fixes? https://github.com/atom/first-mate/issues/106#issue-290073017
