### ISSUE TITLE
Benchmarks do not work

### ISSUE THREAD

**Issue by 50Wliu** [atom/first-mate#91]
Here's the full output of `npm run benchmark` using Node v6.10.1.
```
Tokenizing jQuery v2.0.3
TypeError: Cannot read property 'length' of undefined
    at tokenize (C:\Users\user\Documents\GitHub\first-mate\benchmark\benchmark.coffee:16:3)
    at tokenizeFile (C:\Users\user\Documents\GitHub\first-mate\benchmark\benchmark.coffee:25:3)
    at Object.<anonymous> (C:\Users\user\Documents\GitHub\first-mate\benchmark\benchmark.coffee:27:1)
    at Object.<anonymous> (C:\Users\user\Documents\GitHub\first-mate\benchmark\benchmark.coffee:1:1)
    at Module._compile (module.js:570:32)
    at Object.exports.run (C:\Users\user\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\coffee-script.js:173:23)
    at compileScript (C:\Users\user\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:224:29)
    at compilePath (C:\Users\user\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:174:14)
    at Object.exports.run (C:\Users\user\AppData\Roaming\npm\node_modules\coffee-script\lib\coffee-script\command.js:98:20)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\coffee-script\bin\coffee:7:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
```

The issue appears to be that we're expecting `grammar.tokenizeLines` to return an object that contains the `tags` property, when in fact it returns `value` and `scopes`.

/cc @nathansobo

**Comment by 50Wliu** [comment]
Fixed by #94.
